language: node_js
node_js:
  - "10.16.0"
dist: trusty
sudo: required

branches:
  only:
  - master

before_script:
  - npm install -g @angular/cli
  
script:
  - npm run lint
  - npm run test-headless
  - ng build --prod --base-href https://peter-patocka.github.io/java-angular-client/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/java-angular-client
  on:
    branch: master