language: node_js
node_js:
  - "10.16.0"
dist: trusty
sudo: required

services:
  - docker

addons:
  chrome: stable

branches:
  only:
  - master
  - gh-pages

before_install:
  - LATEST_CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"`
  - curl "https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
  - unzip chromedriver_linux64.zip -d ~/bin

before_script:
  - npm install -g @angular/cli
  - npm install -g angular-cli-ghpages
  - npm install
  
script:
  - npm run lint
  - npm run test-headless
  - npm run e2e

after_success:
  - npm run build
  - ngh