language: node_js
node_js:
  - "10.16.0"
dist: trusty
sudo: required

services:
  - docker

addons:
  chrome: stable

branches:
  only:
  - master

before_install:
  - LATEST_CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"`
  - curl "https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
  - unzip chromedriver_linux64.zip -d ~/bin

before_script:
  - npm install -g @angular/cli
  - npm install

script:
  - npm run lint
  - npm run test-headless
  # - npm run e2e

after_success:
  - npm run build

deploy:
  provider: heroku
  api_key:
    secure: LYE/6j9AmX8wi62YekPP1xaeOmp+wnMwRPAvMNJJTB2kHE7R2dZj73VLoO5xUKOdxVUktzE2nLEXYkwW3T2og9MZUgEh3oWbCVRGUVsIZBrPVC8fKoALyEiPiMCmrAdWf8f7Mu9AxaR7PBGkKGiBmJQ2iUcftzPEcYq0pIa24lJ8VIGDFymBvjrCSURtHj1KPjNna39PxWtbV5oHgyXtIzCf838zw2UOuBYj0iA+jSXruQfiu+4y7B6U6EtL9ZvOXoTFzkD6XG+ftrxz2bG5eGjJd9Fas6/IwAiKglYAaq5u8j7pvvUf5x11b3lsM2sl5hWsPiEhljpEs0/YgoyfZJVdoCEvWUZ7J/MCWQ3WR2hR3pNBfX+YMmvvJFg+bP6e3zgNH34C6GVV/+xDzQnuFwZ7rwwl2LrmlhrirHK7c3JyHGtuj9kFl7eWwV7QXjEYHVY0V92DFm5Oqbubfaajmqo4XWOjPpHe32BKWZdjc4JYXwOZ2ACbkkGqIjMp61exfu3EPZkFeRfqPRfCn+hXyFAEwKJF9XhHk2e0h74uNacnMoq/VOtI1kXP9cBhaxrQ/bUqskxvpc/l28p0hy2mrPXLH5+1SXlGrIEbC/OFdJQErZtDGhe/ZovpJj7NeXFm0f674iHe+DvAsUL97L7tZ2qWT7tjg5X7i89T9mxKIno=
  app: piixon-angular-web
  true: master
