language: node_js
node_js:
  - "10.16.0"
dist: trusty
sudo: required

services:
  - docker

addons:
  chrome: stable

branches:
  only:
  - master

before_install:
  - LATEST_CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"`
  - curl "https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
  - unzip chromedriver_linux64.zip -d ~/bin

before_script:
  - npm install -g @angular/cli
  - npm install
  
script:
  - npm run lint
  - npm run test-headless
  - npm run e2e

after_success:
  - npm run build

before_deploy: "cd dist && echo '{}' > composer.json && echo '<?php include_once(\"index.html\"); ?>' > index.php"

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: piixon-web