language: node_js
node_js:
  - "10.16.0"
dist: trusty
sudo: required

services:
  - docker

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

branches:
  only:
  - master
  - gh-pages

before_script:
  - npm install -g @angular/cli
  - npm install -g angular-cli-ghpages
  - npm install
  
script:
  - npm run lint
  - npm run test-headless
  - npm run e2e

after_success:
  - npm run build
  - ngh